cmake_minimum_required (VERSION 2.8.12)

# Get short filename
string(REGEX MATCH "([^/]+)$" filename ${INPUT_FILE})
# Replace filename spaces & extension separator for C compatibility
# string(REGEX REPLACE "\\.| |-" "_" filename ${filename})
string(REGEX REPLACE "\\.| |-" "_" filename ${filename})
# Convert to lower case
# string(TOLOWER ${filename} filename)
# Read hex data from file
file(READ ${INPUT_FILE} filedata HEX)

if (NOT filedata)
  message(FATAL_ERROR "Error: File '${filedata}' is empty.")
endif()

# Convert hex data for C compatibility
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," filedata ${filedata})

# Append data to c file
file(WRITE ${OUTPUT_C} "/* Autogenerated by bin2c */\n\n")
file(APPEND ${OUTPUT_C} "#include <stdint.h>\n")
file(APPEND ${OUTPUT_C} "#include <vector>\n")
file(APPEND ${OUTPUT_C} "std::vector<uint8_t> ${OUTPUT_VAR} = \n")
file(APPEND ${OUTPUT_C} "{${filedata}};\n")
